### ISSUE TITLE
Update to include CSRF tokens in Handshake

### ISSUE THREAD

**Issue by nanomonkey** [theasp/sente-nodejs-example#6]
Hi, I'm having trouble getting the Express version of this example to work with the current version of Sente.  I believe this is due to how CSRF tokens are managed during the handshake, but it may be due to different csurf, express-session requirements.  Really at this point I'm not sure. As of now my websocket is always downgraded to ajax, despite generating a csrf token within the landing-page via and passing it along when making the connection (instead of nil).

It's my hope that someone that uses Sente with Express has come across this issue and found a fix, but hasn't updated this document.  

Many thanks.

**Comment by nanomonkey** [comment]
Out of curiosity, has this example been tested with the newest Sente?  I see some effort has been made in Sente to include community versions but I'm unsure if they've been battle tested at all.  I'm still using a much older version a the last time I tried to upgrade the connection was downgraded to ajax.

Thanks in advance!

**Comment by theasp** [comment]
Hi,

I've not been keeping the example up to date, which was probably obvious.  I also only use Sente with Macchiato, not Express. In general, there currently is a bug in Sente 1.19.2 that is causing it to not work on NodeJS, I've submitted a PR for that.

PRs welcome for fixing the demo :)

**Comment by nanomonkey** [comment]
I'd love to submit an update to this example, but I've been unable to get any of the latest releases to run correctly.  After updating my dependencies to 
```
                [com.taoensso/encore "3.120.0"]       ; also tried:    "3.62.1" "3.119.0"
                [com.taoensso/sente         "1.18.0"]    ;  "1.19.2"
                [com.taoensso/timbre         "6.2.2"]
```
I get the following errors with running the resultant nodejs server:
```
SHADOW import error /home/nanomonkey/git/scratch/.shadow-cljs/builds/server/dev/out/cljs-runtime/taoensso.sente.js

/home/nanomonkey/git/scratch/out/main.js:64
  /* ignore this, look at stacktrace */ fn.call(global, require, module, __filename, __dirname);
                                           ^
TypeError: goog.global.addEventListener is not a function
    at /home/nanomonkey/git/scratch/.shadow-cljs/builds/server/dev/out/cljs-runtime/taoensso/sente.cljc:1304:4
    at global.SHADOW_IMPORT (/home/nanomonkey/git/scratch/out/main.js:64:44)
    at /home/nanomonkey/git/scratch/out/main.js:1712:1
    at Object.<anonymous> (/home/nanomonkey/git/scratch/out/main.js:1727:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47
```
This may be a problem with my shadow-cljs setup, but it works fine with earlier versions of Sente.

@theasp What versions of Sente are working for you with Macchiato?

**Comment by theasp** [comment]
@nanomonkey the current version works with this PR:  https://github.com/taoensso/sente/pull/453

It looks like this change was introduced with 1.18, 1.17 should work fine too.
